name: learn github action
run-name: ${{github.actor}} is learning github action
on:
  push:
    branches: [main]
jobs:
  do-something-smart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code onto runner
        uses: actions/checkout@v6

      - name: Install Nodejs 
        uses: actions/setup-node@v4
        with:
          node-version: '24.17.0'
          cache: 'yarn'

      - name: enable corepack to manage yarn by Nodejs
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build NuxtJs App
        run: yarn build
      
      - name: Set up SSH on current runner
        run: |
          mkdir -p ~/.ssh 
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{secrets.VPS_HOST}} > ~/.ssh/known_hosts

      - name: Deploy to VPS 
        run: |
          ssh -p ${{secrets.VPS_PORT}} \
          ${{secrets.VPS_USER}}@${{secrets.VPS_HOST}} << 'EOF'
          cd admin-ui-ecommerce/
          git pull
          yarn install --frozen-lockfile
          yarn build
      
      - name: Restart PM2 process
        run: |
          pm2 restart ecommerce-ui
          pm2 log ecommerce-ui 
          pm2 list
          logout

      - name: Done
        run: echo "Deployment completed."