name: learn github action
run-name: ${{github.actor}} is learning github action
on:
  push:
    branches: [main]
jobs:
  do-something-smart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code onto runner
        uses: actions/checkout@v6

      - name: Install Nodejs 
        uses: actions/setup-node@v4
        with:
          node-version: '24.17.0'
          cache: 'yarn'

      - name: enable corepack to manage yarn by Nodejs
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build NuxtJs App
        run: yarn build
      
      - name: Complete
        run: echo "CI done."